# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{movable_type_ar}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["consumersunion"]
  s.date = %q{2010-08-24}
  s.description = %q{An ActiveRecord interface to Movable Type databases.}
  s.email = %q{fostgr@consumer.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/movable_type/ar/author.rb",
     "lib/movable_type/ar/blog.rb",
     "lib/movable_type/ar/category.rb",
     "lib/movable_type/ar/comment.rb",
     "lib/movable_type/ar/database.rb",
     "lib/movable_type/ar/entry.rb",
     "lib/movable_type/ar/fileinfo.rb",
     "lib/movable_type/ar/ipbanlist.rb",
     "lib/movable_type/ar/log.rb",
     "lib/movable_type/ar/notification.rb",
     "lib/movable_type/ar/permission.rb",
     "lib/movable_type/ar/placement.rb",
     "lib/movable_type/ar/template.rb",
     "lib/movable_type/ar/templatemap.rb",
     "lib/movable_type/ar/trackback.rb",
     "lib/movable_type_ar.rb",
     "test/helper.rb",
     "test/test_movable_type_ar.rb"
  ]
  s.homepage = %q{http://github.com/consumersunion/movable_type_ar}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An ActiveRecord interface to Movable Type databases.}
  s.test_files = [
    "test/helper.rb",
     "test/test_movable_type_ar.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

