# Require all model files.
require 'movable_type/ar/database'
require 'movable_type/ar/author'
require 'movable_type/ar/blog'
require 'movable_type/ar/category'
require 'movable_type/ar/comment'
require 'movable_type/ar/entry'
require 'movable_type/ar/fileinfo'
require 'movable_type/ar/ipbanlist'
require 'movable_type/ar/log'
require 'movable_type/ar/notification'
require 'movable_type/ar/permission'
require 'movable_type/ar/placement'
require 'movable_type/ar/template'
require 'movable_type/ar/templatemap'
require 'movable_type/ar/trackback'